### ISSUE TITLE
iJumper 

### ISSUE THREAD

**Issue by woolson** [woolson/app-zhongcao#1]
### 流量监控、插件中心自定义、网速监控、快捷启动

iTunes：[iJumper](https://itunes.apple.com/cn/app/ijumper/id1298439690?mt=8)

<details>
<summary>查看截图</summary>

![](https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/84/b0/a0/84b0a01b-a912-32c7-7e93-63e294c45a14/pr_source.png/460x0w.jpg)
![](https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/8f/aa/f4/8faaf4e9-1224-a893-99cc-ad554a5b7bee/mzl.arcaisjg.png/460x0w.jpg)
</details>

**Comment by woolson** [comment]
### 🐞 2.0.0 beta版 - 快捷方式布局和内部App内不一致

<details>
<summary>查看截图</summary>

![image](https://user-images.githubusercontent.com/27878293/56022214-c752ee80-5d3d-11e9-9bef-fa99eb0cd0cb.png)

![image](https://user-images.githubusercontent.com/27878293/56022225-cae67580-5d3d-11e9-925e-6d95d3368837.png)
</details>

**Comment by woolson** [comment]
### 🤔2.0.0 beta版 - 跳转反馈可关闭声音

**Comment by Gokotx** [comment]
> ### 🐞 2.0.0 beta版 - 快捷方式布局和内部App内不一致
> 查看截图
> ![image](https://user-images.githubusercontent.com/27878293/56022214-c752ee80-5d3d-11e9-9bef-fa99eb0cd0cb.png)
> 
> ![image](https://user-images.githubusercontent.com/27878293/56022225-cae67580-5d3d-11e9-925e-6d95d3368837.png)
内部不一致的问题，可以点击下方的编辑，app列表那边可以选择不同的大小后，通知中心那边就会保持一致了，（这是一个bug，感谢反馈）

**Comment by Gokotx** [comment]
> ### 🤔2.0.0 beta版 - 跳转反馈可关闭声音

这个声音的反馈，我正在考虑是否去除。

**Comment by woolson** [comment]
> > ### 🤔2.0.0 beta版 - 跳转反馈可关闭声音
> 
> 这个声音的反馈，我正在考虑是否去除。

刚刚开会点了一下，有声音吓我一跳。

**Comment by Gokotx** [comment]
> > > ### 🤔2.0.0 beta版 - 跳转反馈可关闭声音
> > 
> > 
> > 这个声音的反馈，我正在考虑是否去除。
> 
> 刚刚开会点了一下，有声音吓我一跳。

哈哈，音量是个问题，手机静音的情况下，不会出声的

**Comment by woolson** [comment]
@Gokotx 通知中心不一致的问题，按上面方法操作还是不行。

**Comment by Gokotx** [comment]
可以先选一个与通知中心不一样的大小，然后点完成，再去通知中心查看 ，还是会显示不一样吗？（有可能是刷新的问题，可以尝试点击通知中心那边的展开和折叠来主动刷新，我这边试了下正常

**Comment by woolson** [comment]
@Gokotx 图标大小是对的（这个一直没问题）， 我的意思是图标的排列不一致（可能是我表达的不到位😂）。

## 问题描述

**软件设置中**：图标大小为中，显示为一行【5】个图标。
**小组件中**：保存软件设置后，显示为一行【4】个图标。

⬇️⬇️ 请看截图 ⬇️⬇️，不知道这样能理解吗？🤪

<details>
<summary>查看截图</summary>

## 软件设置
![image](https://user-images.githubusercontent.com/27878293/56075345-b2d12d80-5df3-11e9-85ed-d9fd9c8cfbf3.png)
## 小组件
![image](https://user-images.githubusercontent.com/27878293/56075350-bf558600-5df3-11e9-9614-fd35f7fac258.png)
</details>

**Comment by Gokotx** [comment]
> @Gokotx 图标大小是对的（这个一直没问题）， 我的意思是图标的排列不一致（可能是我表达的不到位😂）。
> 
> ## 问题描述
> **软件设置中**：图标大小为中，显示为一行【5】个图标。
> **小组件中**：保存软件设置后，显示为一行【4】个图标。
> 
> ⬇️⬇️ 请看截图 ⬇️⬇️，不知道这样能理解吗？🤪
> 
> 查看截图
> ## 软件设置
> ![image](https://user-images.githubusercontent.com/27878293/56075345-b2d12d80-5df3-11e9-85ed-d9fd9c8cfbf3.png)
> 
> ## 小组件
> ![image](https://user-images.githubusercontent.com/27878293/56075350-bf558600-5df3-11e9-9614-fd35f7fac258.png)

我明白你的意思了，我再XSM和7p两种设备上都试过正常的，以为这两种界面的设备都正常，发现在X上有问题，正式版会修复，感谢反馈。

**Comment by woolson** [comment]
@Gokotx 👌。是我傻了，我反馈上没注明我手机型号（XS)，sorry。
